# ##########
work=${HOME}/software
srcdir=../cvc
qlua_build_dir=$(work)/qlua/momproj/build.14.04.1-Ubuntu/

limedir=$(work)/lime/build.14.04.1-Ubuntu/

lemondir=$(work)/lemon/build.14.04.1-Ubuntu/

tmLQCD=$(work)/tmLQCD_main/build.14.04.1-Ubuntu-serial
tmLQCD_src=$(work)/tmLQCD_main/tmLQCD_main

fftwdir=$(work)/fftw/build.14.04.1-Ubuntu
arpackdir=$(qlua_build_dir)/arpack

lapackdir=$(qlua_build_dir)/lapack
lhpcdir=$(qlua_build_dir)/aff


CXX=g++ -fopenmp
CXXFLAGS= -Wall -g -O2 -DF_ -DHAVE_LHPC_AFF -DHAVE_OPENMP 


CCDEP = g++
DEPFLAGS = -MM

INCLUDE = -I$(limedir)/include/ -I$(srcdir) -I$(fftwdir)/include -I. -I$(lhpcdir)/include

LIBS = -L$(lhpcdir)/lib -L$(limedir)/lib/ -L$(fftwdir)/lib -lfftw -llime -llapack -lblas -lgfortran -lm -llhpc-aff

LDFLAGS = -fopenmp -L$(limedir)/lib/ -L$(fftwdir)/lib -lfftw -L/usr/lib/ -llime -llapack -lblas -lgfortran -lm -llhpc-aff


LINK = $(CXX) -o $@ ${LDFLAGS}
COMPILE = ${CXX} $(INCLUDE) -o $@ ${CXXFLAGS}

MODULES = DML_crc32 dml getopt cvc_utils cvc_geometry mpi_init io io_utils propagator_io read_input_parser_cvc \
	  get_index gauge_io contractions_io ranlxd ranlxs Q_phi set_default \
	  Q_clover_phi gsp prepare_source matrix_init project make_x_orbits contract_cvc_tensor smearing_techniques \
	  prepare_propagator scalar_products clover rotations gitversion gamma group_projection


HEADERS = getopt cvc_complex cvc_geometry cvc_linalg iblas icontract cvc_utils default_input_values dml global io io_utils \
	  mpi_init propagator_io read_input_parser get_index gauge_io contractions_io \
	  ranlxd ranlxs Q_phi set_default laplace_linalg Q_clover_phi \
	  gsp prepare_source matrix_init project make_x_orbits contract_cvc_tensor smearing_techniques \
	  prepare_propagator scalar_products clover rotations gamma group_projection


PROGRAM = test_rot_mult_tab


all: dep $(PROGRAM) 


# ##########

read_input_parser_cvc.cpp: ${srcdir}/read_input_parser_cvc.l
	${LEX} -P cvc_ -i -t $< > ${srcdir}/read_input_parser_cvc.cpp

$(addsuffix .d,$(MODULES)): %.d: ${srcdir}/%.cpp
	 @ $(CCDEP) ${DEPFLAGS} ${INCLUDE} $< > $@

$(addsuffix .d,$(PROGRAM)): %.d: ${srcdir}/%.cpp
	 @ $(CCDEP) ${DEPFLAGS} ${INCLUDE} $< > $@

dep: $(addsuffix .d,$(MODULES) ${PROGRAM})

$(addsuffix .o,${MODULES}): %.o: ${srcdir}/%.cpp $(addprefix ${srcdir}/, $(addsuffix .h, ${HEADERS})) %.d
	${COMPILE} ${OPTARGS} -c $< 

$(addsuffix .o,${PROGRAM}): %.o: ${srcdir}/%.cpp %.d
	${COMPILE} ${OPTARGS} -c $< 

${PROGRAM}: %: %.o gitversion.cpp $(addsuffix .o,${MODULES})
	${LINK}  $(addsuffix .o,${MODULES}) $@.o $(LIBS)

gitversion.cpp: ${srcdir}/.git/HEAD ${srcdir}/.git/index
	echo "namespace cvc { const char *g_gitversion = \"$(shell cd ${srcdir} && git rev-parse HEAD && cd -)\"; }" > ${srcdir}/gitversion.cpp

# ##########


clean:
	rm -f *~ *.o *.d $(PROGRAM) ${srcdir}/gitversion.cpp

.PHONY: clean

# ##########
